### ISSUE TITLE
Getting [TypeError: Object #<Object> has no method 'isNumber']

### ISSUE THREAD

**Issue by mapodev** [okaxaki/objc2swift#1]
Error Msg is `[TypeError: Object #<Object> has no method 'isNumber']`

when trying to convert a file.

```
objc2swift Status.m
Preprocess : 293ms
[TypeError: Object #<Object> has no method 'isNumber']
Internal Error
```

**Comment by okaxaki** [comment]
Thank you for reporting. Does the same error occur for any source code? If so, `util.isNumber` method may be missing. Please try to use node v4.4.x or later. 

If the error occurs only with the specific source code, it might be a parser problem. Could I see the source or its fragment? `--stacktrace` option may output useful information for debug. 

```
objc2swift --stacktrace Status.m
```

**Comment by okaxaki** [comment]
I have confirmed that the same error is occured on node v0.12 environment. So it probably a node version problem and I close this issue. 

If the same error is reproduced with node 4.4 or later, please reopen the issue again.
