### ISSUE TITLE
Doesn't support iOS version check

### ISSUE THREAD

**Issue by rostopira** [okaxaki/objc2swift#3]
I think this is enough to describe problem:

```
Syntax Error in ARDAppClient.m
At line 704 column 22
>>   if (@available(iOS 10, *)) {
                        ^
```

**Comment by okaxaki** [comment]
Now supports the @available expression at the commit https://github.com/okaxaki/objc2swift/commit/87f8fcf06a793ce98a521fe5a54837bdc29e3cf1

**Comment by rostopira** [comment]
Awesome, when this version will be released?

**Comment by okaxaki** [comment]
Hi, there's small mistake in the patch above. I have released the correct commit https://github.com/okaxaki/objc2swift/commit/650e70d02aec2bc48ca2c9371cfa16f6f75cd8ba as 0.1.5. Both web and npm package are available.
